name: CI/CD
on:
  pull_request:
    branches:
      - master
jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
         sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << EOF
            cd /Ganttify/Ganttify-Backend-UCF_SD
            git pull origin master
            npm install
            pm2 restart server
          EOF
