name: CI/CD
on:
  pull_request:
    branches:
      - master
jobs:
  my_job:
    name: deploy to DO droplet
    runs-on: ubunbtu-latest
    steps:
      - name: Deploy NodeJS backend
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << EOF
            cd /Ganttify/Ganttify-Backend-UCF_SD
            git pull origin master
            npm install
            pm2 restart server
          EOF
