name: CI/CD
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME : ${{secrets.SSH_USERNAME}}
        run: |
            sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
            pm2 stop all
            cd Ganttify/Ganttify-Backend-UCF_SD
            git restore package.json
            git restore package-lock.json
            git pull origin master
            npm install
            cd ..
            pm2 start ecosystem.config.js
            EOF
